### ISSUE TITLE
База данных Postgres не дожидается выделения IP и не экспортирует IP-адрес при создании

### ISSUE THREAD

**Issue by readonlyden** [timeweb-cloud/terraform-provider-timeweb-cloud#1]
Добрый день, пытаюсь развернуть инфраструктуру с помощью Terraform. Планировал развернуть базу данных PostgreSQL с помощью вашего twc-провайдера, а потом использовать полученные ресурсы в k8s провайдере.

Согласно документации, IP адрес базы экспортируется:
![image](https://user-images.githubusercontent.com/59210489/234558423-7187d0c4-9707-4dc7-9ce4-286dce54cbf0.png)

С помощью terraform создается следующий kubernetes secret:
![image](https://user-images.githubusercontent.com/59210489/234558991-3906fef7-844f-4532-82dc-f6072768910d.png)

Однако при создании ресурса оно не дожидается выделения IP-адреса, в связи с чем secret не содержит IP-адреса хоста
![image](https://user-images.githubusercontent.com/59210489/234559355-85f5173e-9494-4e2d-9d80-8bc22d1499b1.png)

**Comment by timeweb-cloud** [comment]
Здравствуйте!

 Нам очень жаль, что вы столкнулись с подобной проблемой, исправления уже доступны в последней версии провайдера `v0.0.6`.

Для обновления провайдера вы можете воспользоваться командой `terraform init --upgrade`, если по какой-либо причине в данный момент вы не можете выполнить обновление на версию с исправлением, то поможет явное добавления параметра в конфигурацию ресурса создаваемой БД `is_external_ip = true`. 

Спасибо за подробное описание!
