### ISSUE TITLE
Невозможно выбрать проект при создании SSH ключа

### ISSUE THREAD

**Issue by readonlyden** [timeweb-cloud/terraform-provider-timeweb-cloud#12]
Добрый день, на данный момент нельзя нигде указать `project_id `при добавлении SSH ключа:

![image](https://github.com/timeweb-cloud/terraform-provider-timeweb-cloud/assets/59210489/49f7304b-ca48-49b7-9027-3c1b430e8f44)

**Comment by koraga** [comment]
Смотрите внимательнее саму доку. https://github.com/timeweb-cloud/terraform-provider-timeweb-cloud/blob/main/docs/resources/ssh_key.md#примеры-использования

Вы указываете не project_id, а прикрепляете сам ключ к проекту. 
```
# Create new SSH key
resource "twc_ssh_key" "example-key" {
  name = "Example"
  body = file("~/.ssh/some-key.pub")
}

# Usage example of created SSH key
resource "twc_server" "example-server" {
  name = "Example server"
  os_id = data.twc_os.example-os.id

  preset_id = data.twc_presets.example-preset.id

  ssh_keys_ids = [twc_ssh_key.example-key.id]
}
```

**Comment by timeweb-cloud** [comment]
SSH-ключ сейчас можно привязать к серверу, но он не привязывается к конкретному проекту, а шарится между всеми проектами на аккаунте
