### ISSUE TITLE
Load Balancer отмечает атрибут healthcheck как обязательный, хотя в документации указано иначе

### ISSUE THREAD

**Issue by readonlyden** [timeweb-cloud/terraform-provider-timeweb-cloud#13]
Создаю новый load balancer:
```terraform
resource "twc_lb" "lb" {
  name       = "${var.prefix}-${var.env}-lb"
  preset_id  = data.twc_lb_preset.lb_preset.id
  project_id = var.project_id

  ips = [
    for node in data.kubernetes_nodes.nodes.nodes : node.status.0.addresses.0.address
  ]
}
```

Падает с ошибкой:
![image](https://github.com/timeweb-cloud/terraform-provider-timeweb-cloud/assets/59210489/209542aa-be64-42d5-a0ef-ac4a2bb1a483)

А в документации указано иначе:
![image](https://github.com/timeweb-cloud/terraform-provider-timeweb-cloud/assets/59210489/829ce278-f907-4623-a396-bf7ed7b033b8)

**Comment by nikitakolesnikov13** [comment]
@readonlyden мы исправим документацию провайдера, на самом деле есть еще не состыковки. В данном случае это обязательное поле - healthcheck
