### ISSUE TITLE
Невозможно создать кластер с Postgres 15

### ISSUE THREAD

**Issue by yugorshkov** [timeweb-cloud/terraform-provider-timeweb-cloud#16]
`Error: expected type to be one of [mysql mysql5 postgres postgres14 redis mongodb rabbitmq kafka opensearch], got postgres15`
postgres - создаёт 13, postgres14 - 14, 15 через terraform недоступен.

**Comment by scipe** [comment]
@yugorshkov you might can use same workaround as here: https://github.com/timeweb-cloud/terraform-provider-timeweb-cloud/issues/19 kinda crazy but at least something

**Comment by nikitakolesnikov13** [comment]
добавили все доступные версии
