### ISSUE TITLE
Cant create VPC in NL

### ISSUE THREAD

**Issue by scipe** [timeweb-cloud/terraform-provider-timeweb-cloud#19]
Error: expected location to be one of [ru-1 pl-1], got eu-1

**Comment by scipe** [comment]
Workaround: create vpc manually, import it and add location to lifecycle ignore.

**Comment by trombonax** [comment]
I have same issue, still not fixed

**Comment by mfbeach** [comment]
Should be fixed in 1.3.9 release.
