### ISSUE TITLE
Где исходный код?

### ISSUE THREAD

**Issue by SergeyDjam** [timeweb-cloud/terraform-provider-timeweb-cloud#20]
Подскажите, где исходный код? Почему распространяются только бинарники, и какая тогда лицензия?

**Comment by timeweb-cloud** [comment]
У нас нет сейчас планов открыть исходный код провайдера, но мы постараемся вернуться к этому вопросу в следующем году 🙄

**Comment by tazjin** [comment]
Здравствуйте! Во многих случаях не очень хочется (или, даже невозможно) скачать какие-то закрытые бинарники.

Нам для наших opensource-проектов хотелось бы переехать на DNS от Timeweb (вместе с нашим новым выделенным сервером у вас), но без открытого кода мы этот провайдер использовать не можем.
