### ISSUE TITLE
Некорректное поведение при удалении ресурса НЕ через terraform

### ISSUE THREAD

**Issue by morggoth** [timeweb-cloud/terraform-provider-timeweb-cloud#3]
Здравствуйте. 

Если удалить руками ресурс, созданный при помощи провайдера и затем заново запустить terraform, он будет падать с ошибкой:

`│ Error: can't receive server: can't receive server: not found: status_code: 404, message: Server with id: 1762367 is not found, error_code: server_not_found, response_id: 3331b334-4f2a-4269-980b-825750af8f91`

хотя предполагается, что при отсутствии ресурса, который с точки зрения terraform`а _должен_ существовать, он будет пытаться создать его заново.

**Comment by timeweb-cloud** [comment]
Здравствуйте!

Просим прощения за долгий ответ.

При разработке провайдера учитывались возможные проблемы, которые могли бы возникнуть у провайдера при взаимодействии. На текущий момент было принято решение, что пропажа ресурса, о котором есть информация в состоянии Terraform, считается в большинстве случаев неожиданным поведением. 

При необходимости убрать информацию о ресурсе из состояния Terraform, который был удален через ПУ или API, можно воспользоваться командами управления состояниемю. Информация о них доступна по команде `terraform state --help`
