### ISSUE TITLE
Указание параметру `software_id` значения `null`

### ISSUE THREAD

**Issue by deff-dev** [timeweb-cloud/terraform-provider-timeweb-cloud#6]
Здравствуйте.

Добавьте возможность указать `null` значение параметра `software_id` в [twc_server](https://registry.terraform.io/providers/timeweb-cloud/timeweb-cloud/latest/docs/resources/server), как сделано это с `ssh_keys_ids`. На текущий момент в случае указания `null`  параметр `software_id` равен 2, таким образом выходит что на сервер устанавливается ПО ID которого равно этому значению.

Ожидаемый результат:

В случае если значение параметра `software_id`  равно `null`, то мы игнорируем его, по аналогии с `ssh_keys_ids`.

P.S Данный функционал необходим для моего [модуля](https://github.com/deff-dev/terraform-timeweb-cloud-server). Хочу дать возможность пользователю при конфигурации указать будет ли у него установлено на сервер дополнительное ПО с вашего маркетплейса, или же нет.

**Comment by mfbeach** [comment]
Здравствуйте! 

Попробовали с таким манифестом: 
```
data "twc_presets" "example-preset" {
  price_filter {
    from = 300
    to   = 400
  }
}

data "twc_os" "example-os" {
  name    = "ubuntu"
  version = "22.04"
}

resource "twc_server" "example" {
  name        = "FROM TF"
  software_id = null

  os_id     = data.twc_os.example-os.id
  preset_id = data.twc_presets.example-preset.id

}
```

Воспроизвести не удалось. На конфигураторе тоже не воспроизводится. 
Скорее всего проблема была когда-то давно и уже неактуальна. Если все-таки как-то удастся воспроизвести, то приложите, пожалуйста, манифест на котором воспроизводится.
