### ISSUE TITLE
Возможность связать ноды Kubernetes и Load Balancer через Terraform

### ISSUE THREAD

**Issue by readonlyden** [timeweb-cloud/terraform-provider-timeweb-cloud#7]
На данный момент при создании K8S Node Group через терраформ нельзя получить IP-адреса нод, чтобы указать их в балансировщике. 

Экспорт IP-адресов нод  позволит как связать их с балансировщиком и связать домен с кластером.

**Comment by scipe** [comment]
@readonlyden можно использовать data из k8s провайдера и получить айпишники из ингресса nginx

**Comment by nikitakolesnikov13** [comment]
@readonlyden На сегодня можем предложить вам создавать loadbalancer средствами cloud controller manager. Это реализовано путем создание обычного  сервиса kubernetes с type: loadbalancer.
