### ISSUE TITLE
Нет возможности управлять публичным доступом к PosgtreSQL

### ISSUE THREAD

**Issue by readonlyden** [timeweb-cloud/terraform-provider-timeweb-cloud#8]
На данный момент при создании БД она создается с доступом исключительно из приватной сети.

`is_external_ip` - отключает доступ к БД из приватной сети и включает доступ из публичной, но нет возможности оставить И приватную, И публичную.

Предлагаю добавить возможность разрешать доступ  из публичной сети с оставлением доступа из приватной с помощью флага `allow_external_ip` (или что-то подобное).

**Comment by readonlyden** [comment]
Поигрался с параметром - всё таки да, он делает то, что нужно, тогда достаточно поправить его описание или переименовать в `allow_external_ip`

**Comment by timeweb-cloud** [comment]
Здравствуйте! Скорректировали описание параметра.
